#pragma once

#include <stdbool.h>
#include <stdint.h>

typedef struct {
    bool fix_valid;
    bool gnss_online;
    bool gnss_gga_seen;
    char gnss_rmc_status;
    int gnss_gga_quality;
    bool wifi_connected;
    bool mqtt_connected;
    bool time_trusted;
    bool binding_ready;
    bool binding_known;
    bool binding_bound;
    char binding_code[7];
    int64_t binding_expires_ms;
    char wifi_ssid[33];
    char wifi_ip[16];
    int wifi_rssi;
    bool sim_ready;
    bool cellular_registered;
    bool cellular_data_ready;
    int cellular_csq;
    uint32_t cellular_reconnects;
    int64_t cellular_sampled_ms;
    char cellular_model[40];
    char cellular_carrier[24];
    char cellular_error[40];
    int satellites;
    float hdop;
    bool gsv_seen;
    int gsv_peak_in_view;
    int gsv_peak_snr;
    float speed_kmh;
    uint32_t fix_age_ms;
    unsigned queue_depth;
    unsigned queue_dropped;
} demo_status_t;
